name: Pipeline CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build_ecr: 
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout 
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::461546078282:role/githubAction4
          aws-region: us-east-2

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build Image
        run: | 
          docker build -t meu-site:v1.0 .
          docker tag meu-site:v1.0 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
          docker push 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0

  job2:
    name: Deploy EC2 SSH
    needs: build_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5.0.0

      # 1. Essa Action configura o agente SSH, cria o arquivo e aplica o chmod correto automaticamente
      - name: Configurar Chave SSH Nativamente
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.INSTANCE_KEY }}

      # 2. Executa os comandos diretamente na EC2 sem precisar gerenciar o arquivo .pem
      - name: Conectar na EC2 e rodar os comandos
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.PUBLIC_IP }} << 'EOF'
            
            # Comandos executados DENTRO da EC2
            aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin 461546078282.dkr.ecr.us-east-2.amazonaws.com
            
            sudo docker pull 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
            
            sudo docker stop site || true
            sudo docker rm site || true
            
            sudo docker run -d -p 80:80 --name site 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
            sudo docker ps
          EOF