name: Pipeline CI/CD

on: 
  push:
    branches:
      - main

jobs: # CORRIGIDO: Colado na parede esquerda
  build_ecr: 
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout 
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::461546078282:role/githubAction4
          aws-region: us-east-2

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build Image
        run: | 
          docker build -t meu-site:v1.0 .
          docker tag meu-site:v1.0 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
          docker push 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0

  job2:
    name: deploy-ec2
    needs: build_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Deploy EC2 SSH
        run: |
          
          echo "${{ secrets.INSTANCE_KEY }}" > chavekey.pem
          
          
          chmod 400 chavekey.pem
          
          
          ssh -i chavekey.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.PUBLIC_IP }} << 'EOF'
            
           
            aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin 461546078282.dkr.ecr.us-east-2.amazonaws.com
            
            sudo docker pull 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
            
            sudo docker stop site || true
            sudo docker rm site || true
            
            sudo docker run -d -p 80:80 --name site 461546078282.dkr.ecr.us-east-2.amazonaws.com/site_prod:v1.0
            sudo docker ps
          EOF
          
          
          rm -f chavekey.pem